clc;
clear all;
close all;
fs = 1000;
fc = 100;
fm = 10;
t = 0:1/fs:1;
vc = 7;
vm = 5;
message_signal = vm*sin(2*pi*fm*t);
carrier_signal = vc*sin(2*pi*fc*t);
m = 1;
st = vc*sin(2*pi*fc*t + m.*sin(2*pi*fm*t));
subplot(4,1,1);
plot(t, message_signal);
subplot(4,1,2);
plot(t, carrier_signal);
subplot(4,1,3);
plot(t, st);
grid on;
